Survey.delete_all
SurveyQuestionGroup.delete_all
SurveyQuestion.delete_all
SurveyQuestionResponse.delete_all


Survey.new(:name => "Team V Appliation Form", :description => "").save
Survey.first.question_groups.build(:heading_text => "Hi {{first_name}} \n\nThank you for your interest in the Team v programme. We're over the moon that you want to join the team and help us to change the world, one campaign at a time. \n\n Please complete all sections of the application as fully as possible and remember to read the role description before you apply. \n\n Got any questions? Pop us an email at teamv@vinspired.com or call us on 020 7960 7039. \n\n Best of luck! \n\n Stephanie and the Team v staff team").save
Survey.first.question_groups.build(:heading => "SKILLS AND QUALITIES", :heading_text => "We’re looking for enthusaistic and creative future leaders. We offer a world-class training package, designed to allow you to grow and develop over the year. \n\n Competition is likely to be tough and this is your chance to tell us why you deserve to be shortlisted for an interview. Please answer these four questions as fully and succinctly as you can.").save
Survey.first.question_groups[1].questions.build(:name => "A big part of this role will involve inspiring other young people to join your team and help you run local your campaigns. How you would engage them and keep them motivated? (200 word limit)", :field_type => 'text', :required => true).save
Survey.first.question_groups[1].questions.build(:name => "Please tell us about a social issue in your community that you feel strongly about. What would you do to address it? (200 word limit)", :field_type => 'text', :required => true).save
Survey.first.question_groups[1].questions.build(:name => "Tell us about a time when you have committed to reaching a specific goal. What was your goal and how did you achieve it? (200 word limit)", :field_type => 'text', :required => true).save
Survey.first.question_groups[1].questions.build(:name => "Describe a time you were faced with a problem. What steps did you take to overcome it? (200 word limit)", :field_type => 'text', :required => true).save
Survey.first.question_groups.build(:heading => "YOUR MOTIVATION", :heading_text => "We want to understand what makes you tick to ensure that the programme works for you. Please complete the three questions below and tell us why you want to join Team v and change the world, one campaign at a time.").save
Survey.first.question_groups[2].questions.build(:name => "Why do you want to be part of Team v? (100 word limit)", :field_type => 'text', :required => true).save
Survey.first.question_groups[2].questions.build(:name => "What do you expect to get out of being a Team v Leader? (100 word limit)", :field_type => 'text', :required => true).save
Survey.first.question_groups[2].questions.build(:name => "And finally… tell us about someone (real or fictional) that inspires you and why (100 word limit)", :field_type => 'text', :required => true).save
Survey.first.question_groups.build(:heading => "MORE ABOUT YOU", :heading_text => "To help us plan our selection days and how the programme will run from September, please answer the following questions as accurately as possible.").save
Survey.first.question_groups[3].questions.build(:name => "Where did you hear about Team v? (Tick all that apply)", :field_type => 'check_boxes_with_other', :required => true, :options => ["vInspired.com","Email","A current or previous Team v Leader","Volunteer Centre","Another national volunteering programme","Facebook","Twitter","Google"]).save
Survey.first.question_groups[3].questions.build(:name => "What is your home postcode?", :field_type => 'string', :required => true, :default_to => 'postcode').save
Survey.first.question_groups[3].questions.build(:name => "Which region will you be in during term times from September 2014 to May 2015", :field_type => 'radio', :required => true, :options => ["North East", "North West", "Yorkshire & Humber", "East Midlands", "West Midlands", "East of England", "South East (not London)", "South West", "London (north of the river)", "London (south of the river)"]).save
Survey.first.question_groups[3].questions.build(:name => "What is your gender?", :field_type => 'radio', :required => true, :options => ["Male", "Female", "Other"]).save
Survey.first.question_groups[3].questions.build(:name => "On which of the following dates could you attend a Team v selection day? (tick all that apply)", :field_type => 'check_boxes', :required => true, :options => ["Wednesday 2 July - London", "Friday 4 July – Leeds", "Saturday 5 July – Manchester", "Friday 11 July – Birmingham", "Saturday 12 July – Birmingham", "Wednesday 16 July – Ipswich", "Friday 18 July – Southampton", "I am flexible", "I cannot make any of the above dates"]).save
Survey.first.question_groups[3].questions.build(:name => "Is an AM (10am-1pm), PM (2pm-5pm), or evening (5pm-8pm) slot better for you?", :field_type => 'radio', :required => true, :options => ["AM", "PM", "Evening", "Any"]).save
Survey.first.question_groups[3].questions.build(:name => "What phone number can we contact you on should you be invited to a selection day? (preferably mobile) ", :field_type => 'string', :required => true, :default_to => 'phone').save
Survey.first.question_groups.build(:heading => "DECLARATION", :heading_text => "Welcome to the final section! Please answer the questions below as best you can. Don't worry about ticking 'No' or 'Don't know' to the event dates below - we can discuss this in more detail at selection day should you be shortlisted.Once you're done and you're happy with your answers here and on previous pages, click submit!").save
Survey.first.question_groups[4].questions.build(:name => "I can commit to the Team v programme from 13 September 2014 to 31 May 2015", :field_type => 'radio', :required => true, :options => ['Yes', 'No']).save
Survey.first.question_groups[4].questions.build(:name => "I am able to attend the Team v Induction Day on Saturday 13 September 2014", :field_type => 'radio', :required => true, :options => ['Yes', 'No', "Not Sure"] ).save
Survey.first.question_groups[4].questions.build(:name => "I am able to attend the first Team v Residential from Friday 17 October to Sunday 19 October 2014", :field_type => 'radio', :required => true, :options => ['Yes', 'No', "Not Sure"] ).save
Survey.first.question_groups[4].questions.build(:name => "I confirm that the information given in this application form is true and correct to the best of my knowledge", :field_type => 'radio', :required => true, :options => ['Yes', 'No'] ).save
